[package]
name = "othello-uefi-loader"
version = "0.1.0"
edition = "2021"

[dependencies]
uefi = { version = "0.36.1", features = ["alloc", "global_allocator", "logger", "panic_handler"] }
log = "0.4"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
